package cli

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// opencodePluginTemplate is the shim plugin `fence init opencode` installs.
// OpenCode has no hooks file to converge — its extension point is a JS plugin
// — so init renders this template (binary path + quiet flag) and writes it
// whole; re-running init regenerates it, which is also how a stale binary
// path heals and the quiet toggle flips.
//
//go:embed opencode_plugin.js
var opencodePluginTemplate string

// opencodeMarker identifies a plugin file as ours, the way containsHook does
// for JSON hook entries. Install and uninstall refuse to touch a fence.js
// that lacks it — that file belongs to the user, not to us.
const opencodeMarker = "generated by `fence init opencode`"

// opencodePluginPath returns where the shim lives: the project's
// .opencode/plugins/, or with global the user-level plugins dir. OpenCode
// follows XDG on every platform (~/.config/opencode, not ~/.opencode), so
// this cannot go through settingsPath like the JSON-hooks agents.
func opencodePluginPath(global bool) (string, error) {
	if !global {
		wd, err := os.Getwd()
		if err != nil {
			return "", err
		}
		return filepath.Join(wd, ".opencode", "plugins", "fence.js"), nil
	}
	cfg := os.Getenv("XDG_CONFIG_HOME")
	if cfg == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		cfg = filepath.Join(home, ".config")
	}
	return filepath.Join(cfg, "opencode", "plugins", "fence.js"), nil
}

// renderOpencodePlugin fills the template with the current binary and the
// quiet toggle. The path is JSON-encoded because it lands inside a JS string
// literal.
func renderOpencodePlugin(quiet bool) []byte {
	binJSON, _ := json.Marshal(fenceBinary())
	out := strings.Replace(opencodePluginTemplate, "{{FENCE_BIN}}", string(binJSON), 1)
	out = strings.Replace(out, "{{QUIET}}", fmt.Sprintf("%t", quiet), 1)
	return []byte(out)
}

// installOpencodePlugin writes the rendered shim at path. Like installHooks
// it is idempotent and convergent: an identical file is untouched, a stale
// one (old binary path, different quiet flag, older shim) is regenerated, and
// a fence.js we did not generate is refused rather than clobbered.
func installOpencodePlugin(path string, quiet bool) (hookInstallResult, error) {
	desired := renderOpencodePlugin(quiet)

	existing, err := os.ReadFile(path)
	switch {
	case err == nil:
		if bytes.Equal(existing, desired) {
			return hookUnchanged, nil
		}
		if !bytes.Contains(existing, []byte(opencodeMarker)) {
			return hookUnchanged, fmt.Errorf("%s exists but was not generated by fence — move it out of the way first", path)
		}
		if err := os.WriteFile(path, desired, 0o644); err != nil {
			return hookUnchanged, err
		}
		return hookUpdated, nil
	case os.IsNotExist(err):
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return hookUnchanged, err
		}
		if err := os.WriteFile(path, desired, 0o644); err != nil {
			return hookUnchanged, err
		}
		return hookInstalled, nil
	default:
		return hookUnchanged, err
	}
}

// removeOpencodePlugin deletes the shim at path if it is ours, mirroring
// removeHooks: nothing to remove is not an error, but a fence.js the user
// wrote themselves is never deleted.
func removeOpencodePlugin(path string) (hookRemoveResult, error) {
	existing, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return hookAbsent, nil
		}
		return hookAbsent, err
	}
	if !bytes.Contains(existing, []byte(opencodeMarker)) {
		return hookAbsent, fmt.Errorf("%s was not generated by fence — refusing to delete it", path)
	}
	if err := os.Remove(path); err != nil {
		return hookAbsent, err
	}
	return hookRemoved, nil
}
