// fence.js — generated by `fence init opencode`; re-run it to update, or run
// `fence uninstall opencode` to remove. Do not hand-edit.
//
// Pipes each tool call to `fence hook opencode` and enforces the decision.
// OpenCode's tool.execute.before hook has exactly one block primitive —
// throwing — so deny and ask both throw (an ask message tells the model to
// get the user's confirmation instead of retrying). Warn and allow notices
// surface as toasts. Fails open: if fence is missing or errors, the call
// proceeds as if Fence were not installed.

const fenceBin = {{FENCE_BIN}}
const quiet = {{QUIET}}

// The tools Fence evaluates; everything else proceeds without a subprocess.
const screened = new Set(["bash", "edit", "write", "read", "apply_patch", "webfetch"])

export const Fence = async ({ $, client, directory }) => {
  const fence = async (args, payload) => {
    const proc = await $`${fenceBin} hook opencode ${args} < ${new Response(payload)}`
      .quiet()
      .nothrow()
    if (proc.exitCode !== 0) return undefined // fail open
    const text = proc.stdout.toString().trim()
    return text ? JSON.parse(text) : undefined
  }

  const toast = async (message, variant) => {
    try {
      await client.tui.showToast({ body: { message, variant } })
    } catch {} // best-effort: enforcement never depends on the TUI
  }

  return {
    // Session lifecycle reaches plugins only through the generic event hook —
    // "session.created" is not a top-level hook key and would be silently
    // ignored (see Hooks in @opencode-ai/plugin).
    event: async ({ event }) => {
      try {
        if (event.type !== "session.created") return
        if (event.properties?.info?.parentID) return // subagents inherit the parent session's banner
        const res = await fence(["session-start"], "")
        if (res?.message) await toast(res.message, "info")
      } catch {} // the banner must never break a session
    },

    "tool.execute.before": async (input, output) => {
      let res
      try {
        if (!screened.has(input.tool)) return
        res = await fence(
          quiet ? ["--quiet"] : [],
          JSON.stringify({ cwd: directory, tool_name: input.tool, tool_input: output.args }),
        )
      } catch {
        return // fail open — a guardrail must never brick the agent it protects
      }
      if (!res) return
      if (res.decision === "deny" || res.decision === "ask") {
        throw new Error(res.message)
      }
      if (res.message) await toast(res.message, res.decision === "warn" ? "warning" : "info")
    },
  }
}
